services:
  postgres:
    image : 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=haouate20010811
      - POSTGRES_DB=myrh
    ports:
      - 5432
  spring-app :
    build :
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myrh
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=haouate20010811
      - SPRING_JPA_HIBERNATE_DDL_AUTO= update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587