spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myrh
    username: abderrahman
    password: haouate20010811
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: static/files
  mail:
    host: smtp.gmail.com
    port: 587
    username: Abderrahmanehaouate@gmail.com
    password: ipsi hekl ecwr lqdv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
